### ISSUE TITLE
有一个Bug，影响el-dialog中的el-select

### ISSUE THREAD

**Issue by imageslr** [dwqs/vue-area-linkage#1]
如题，不知道是不是bug。但是我在没有引用这个库的时候，el-select-dropdown的z-index比v-modal高，会显示出来：

![image](https://user-images.githubusercontent.com/17822028/29487068-1f26f184-8526-11e7-84d1-166e2c7eae2b.png)

而如果我引用了这个库，el-select-dropdown的z-index就变得和v-modal一样了，无法显示在顶层，必须点第二次才会让el-select-dropdown的z-index比v-modal大，然后显示出来：
![image](https://user-images.githubusercontent.com/17822028/29487059-e0e3b70e-8525-11e7-9c8d-a8df22c715a9.png)

今天排查好久才排查出原因，目前不知道具体是为什么。

**Comment by dwqs** [comment]
z-index 的值是 element-ui 通过 js 动态写入的  这个是 element-ui 在多层嵌套中自身的 bug  一个解决方式是 在你打开 dialog 的时候  动态将 v-modal 的 z-index 设置在 2000 以内

**Comment by imageslr** [comment]
嗯，但是如果在dialog中使用原生el-select就不会被覆盖，而用area-select就会被覆盖。后者不也是给el-select传递数组吗？

**Comment by dwqs** [comment]
我引入  element 是按需引入的 不是全量引入  所以会有 z-index 覆盖的问题 这个我在项目中有碰到过  解决方式就是通过 js 再将 v-modal 的 z-index 设置在 2000 以内。   这个之前有人给 element 提过 Issue 不过貌似不了了之了。 

area-select 传给 el-select 的是数组

**Comment by dwqs** [comment]
通过 js 再将 v-modal 的 z-index 设置在 2000 以内时  需要设置个定时器去拿 v-modal 元素, 因为 dialog 有过渡动画  在打开 dialog 立即去拿 v-modal 可能会获取不到这个 dom 元素

**Comment by imageslr** [comment]
嗯好的 这个我可以在dialog的哦；p
