### ISSUE TITLE
    <area-cascader type='all' v-model="three" :level='3'></area-cascader>

### ISSUE THREAD

**Issue by JinGits** [dwqs/vue-area-linkage#11]
Invalid prop: custom validator check failed for prop "level".
报的这个错误，在data里面申明 也是报这个错 怎么回事啊

**Comment by dwqs** [comment]
哪个版本？能把控制台的报错截图看下吗

**Comment by JinGits** [comment]
在 2018-01-12 18:26:56，"Pomy" <notifications@github.com> 写道：


哪个版本？能把控制台的报错截图看下吗

**Comment by JinGits** [comment]
![Uploading image (2).png…]()
![Uploading image.png…]()

**Comment by JinGits** [comment]
"vue": "^2.3.3",
    "vue-area-linkage": "^1.2.5", 版本
  <area-cascader type='all' v-model="three" :level="3"></area-cascader> 代码
Invalid prop: custom validator check failed for prop "level". 报错

**Comment by dwqs** [comment]
控制台的报错信息能否截个图给看下？还有你的用例代码

**Comment by JinGits** [comment]
用例代码如下 
<area-cascader type='all' v-model="three" :level="3"></area-cascader>
报错信息如下
Invalid prop: custom validator check failed for prop "level".

**Comment by dwqs** [comment]
对于 `area-cascader` 组件，`level` 属性只接受 0 和 1, 0表示二联，1是三联
```
level: {
           type: Number,
           default: 0, // 0->二联 1->三联 
            validator: (val) => [0, 1].indexOf(val) > -1
 },
```
