### ISSUE TITLE
你好,我升级到1.2.6 无法使用change事件啊

### ISSUE THREAD

**Issue by JinGits** [dwqs/vue-area-linkage#13]
怎么能联系到您呢？ 给你贴下用例代码

**Comment by dwqs** [comment]
可以的：

```
<area-select v-model="selected" @change="testChange"></area-select>
```

**Comment by JinGits** [comment]
`<area-select v-model='selectedList' @change="testChange"></area-select>`
` selectedList:[],`
```
  testChange(v){
          console.log(v)
      },
```
`   "vue-area-linkage": "^1.2.6",`
用例代码如上 打印不出来值

**Comment by dwqs** [comment]
你把 vue-area-linage uninstall 之后重新装试试

**Comment by dwqs** [comment]
长时间无响应 关闭
