### ISSUE TITLE
多页面中直接引用安装后dist文件中的index文件

### ISSUE THREAD

**Issue by airzhanglin** [dwqs/vue-area-linkage#14]
多页面中直接引用安装后dist文件中的index文件怎么不行

**Comment by dwqs** [comment]
1. 请提供下代码
2. 如果有报错  请提供下错误信息

**Comment by airzhanglin** [comment]
<template>
                                <area-select :level="2" v-model="selected"></area-select>
                            </template>
<script src="{{URL::asset('admin/js/plugin/vue-area/index.js')}}"></script>
<script>
new Vue({
el:'.page-content',
data:{
 selected:["440000","440300","440305"],
}
})
</script>
没有报错

**Comment by dwqs** [comment]
你手动安装一下试试吧   组件没有检测 window 环境进行自动安装

**Comment by airzhanglin** [comment]
我是手动手动安装的啊，然后再拿出dist文件里放到自己的项目中。

**Comment by dwqs** [comment]
http://onasvjoyz.bkt.clouddn.com/area.min.js  你下载一下这个 js 文件
