### ISSUE TITLE
你好 请问下引入你这个组件之后，相当于把elementui 又引入了一遍，这样ui就重复了啊

### ISSUE THREAD

**Issue by JinGits** [dwqs/vue-area-linkage#15]
![image](https://user-images.githubusercontent.com/20101163/35378489-f0dcf892-01ed-11e8-8784-fa7d40b331b4.png)

**Comment by JinGits** [comment]
而且还有个问题就是 就是如果用对话框的形式，z-index 有时候会比对话框的那个z-index 小 导致不会出现，不知道什么问题

**Comment by dwqs** [comment]
1. 我对 elementui 是按需引入的
2. z-index 的问题可以看下 [#1](https://github.com/dwqs/vue-area-linkage/issues/1)
