### ISSUE TITLE
设置默认值问题

### ISSUE THREAD

**Issue by dafeng17** [dwqs/vue-area-linkage#16]
- 
![default](https://user-images.githubusercontent.com/17774547/35381623-de8ae1c2-01f7-11e8-871d-7d83627ba5d5.png)
请问这样是不是不能设置默认值？

**Comment by dwqs** [comment]
是的  你可以改为下面的格式试试：

```js
[110000, 110100, 110101]  或者 ["北京市", "市辖区", "东城区"]
```

**Comment by dwqs** [comment]
长时间无回应
