### ISSUE TITLE
已经设置了默认值之后，再次动态改变里面的选项值失败

### ISSUE THREAD

**Issue by liuyb** [dwqs/vue-area-linkage#17]
第一次改变了控件的值比如改成了  广西壮族自治区  > 柳州市 >  柳南区
第二次改变控件的值的时候，就不再生效，一直显示的是  广西壮族自治区  > 柳州市 >  柳南区

请问这是bug，还是写法不对？

**Comment by dwqs** [comment]
请提供相关示例或者 查看 demo: https://dwqs.github.io/vue-area-linkage/ 示例

**Comment by dwqs** [comment]
长时间无响应 关闭
