### ISSUE TITLE
有清空之前选择的数据的方法吗？

### ISSUE THREAD

**Issue by DeloYong** [dwqs/vue-area-linkage#19]
设置this.selected = [] 是无效的

**Comment by dwqs** [comment]
暂时没有

**Comment by tudanqz** [comment]
那只能操作dom了  _this.$refs.areacascader.$vnode.elm.firstChild.childNodes[0].innerText = '请选择'

**Comment by fxs-space** [comment]
今天我用这个插件时，也遇到了这个问题，最后想出用“v-if”先暂时性解决问题。
`<area-select v-if="showAreaLinkage" type="text" v-model="areaName" :data="pca"
                                         :placeholders="['请选择省份','请选择市区']"></area-select>`
`data() {
            return {
                showAreaLinkage: true,
                areaName: []
            };
        },`
`methods: {
            clickResetBtn() {
                this.showAreaLinkage = false;
                this.areaName = [];
                setTimeout(() => {
                    this.showAreaLinkage = true;
                }, 0);
            }
}`

**Comment by dwqs** [comment]
因为联动时，有好几个 Input 框，如果要加一个清空的方法，我目前没想到该怎么加？如果你们有好的建议，欢迎提供。 @FengXianSen  @tudanqz

**Comment by Linkontoask** [comment]
vue已经实现双向绑定，楼主可以看看[我之前回复](https://github.com/dwqs/vue-area-linkage/issues/47#issuecomment-489322707)
