### ISSUE TITLE
在 element ui 的对话框中使用，下拉框会被对话框挡住

### ISSUE THREAD

**Issue by zhouqitong** [dwqs/vue-area-linkage#20]
在 element ui 的对话框中使用，下拉框会被对话框挡住，如图所示：

![image](https://user-images.githubusercontent.com/16068104/35777685-2c398f20-09ed-11e8-9d8f-07237663fa8a.png)

**Comment by dwqs** [comment]
应该是 z-index 值的问题 相关 issue #1

**Comment by zhouqitong** [comment]
@dwqs 对框框的style不能直接修改
