### ISSUE TITLE
ReferenceError: window is not defined 

### ISSUE THREAD

**Issue by jl1014171068** [dwqs/vue-area-linkage#22]
vue version
v2.5.15

"nuxt": "^1.0.0"

![image](https://user-images.githubusercontent.com/12130044/37267122-434c876c-25f9-11e8-8baf-9954b0ec571f.png)

在nuxt官网提示解决方法：
![image](https://user-images.githubusercontent.com/12130044/37267143-60817248-25f9-11e8-8592-0c7d34b6eea5.png)
但是在我这边没办法去使用
if(process.browser){}

**Comment by jl1014171068** [comment]
// .vue 页面
if (process.browser) {
var 组件 = require('组件')
Vue.use(组件)
Vue.component('组件', 组件)
}

// nuxt.config.js
build: {
vendor: ['组件']
}

**Comment by dwqs** [comment]
提错地方了？
