### ISSUE TITLE
可否在提出一层抽象以便适用于任何联动

### ISSUE THREAD

**Issue by rplees** [dwqs/vue-area-linkage#24]
你好,我有个想法,就是在 省-市-区-街道 再提出一层抽象,就是 UI + data = 联动,其中data有可能是2-4层之间,提供的json的数据 省[key1] - 市[key2]-区[key3]..., 其中key1,2,3...是可以自定义的,自定义的key并与json的key是一致的!这样就可以适用于了任何联动了,比如网站自定义,经营类型,省区等...

**Comment by dwqs** [comment]
你是意思是   我只给 UI 然后 data 数据由调用方提供   然后按照约定来配置 `value` 和 `key` ?

**Comment by rplees** [comment]
@dwqs 是的,这样的话这份数据是后端给的,这好编辑/修改,就想省区市联动,就算前端持有数据,其实后端也会有一份一样的数据.数据是外部引入的话就可以定制联动了

**Comment by dwqs** [comment]
这个 idea 可以   我会先写个 demo 看看

**Comment by rplees** [comment]
@dwqs 好的,期待种...

**Comment by dwqs** [comment]
对于多级联动  那怎么约束调用方的 data 呢？因为联动的数据调用方应该都是按照某中格式组织好了的  如果按照我约定的格式传递数据  这可能会导致调用方会重新梳理一遍数据   我觉得这个对调用方不太友好 @rplees

**Comment by rplees** [comment]
@dwqs 您好,我有个思路是怎么去取到自己想要的data,不知道是否可行,data有2种格式
## 第一种统一格式(组件内部定义的),其中 items 是约定这样的
```js
data = [
	{'键1' : '值1', items: [{
		'item0键1' : 'item0值1', items:[{}...]
	}...
]}
...
]
```
## 还有二种当用户自定义的时候如:
```
data = [
{
	cKey:'键1'
	cText:'值1',
	cItems:[
		{cKey:'item0键1', cText:'item0值1', cItems:[{}...]}...
	]
} ....
]
```
可以加上一个约定来定义怎么取,其实最终转换成组件的格式(第一种格式)
```js
data-schema = [ {key:'cKey',value:'cText', items:'cItems'}... ] 
//或者 
data-schema = {key:'cKey',value:'cText', items:'cItems' }
```
如果3级联动 data-schema 只定义了 1 个长度, 则每级都采用系统的格式,
意思就是 
```js
if(当前第几级 <= level) {
	let curr-data-schema = data-schema[当前第几级] || data-schema[0]	
}
```


_注: 第二种格式加个转换的方法变成第一种数据,组件内部就一直使用第一种格式的data_

### 组件其他属性都应该不需要去修改

- level
- type - text/code/all
- placeholder=['选择省', '选择市']
- v-model - Vue
- defaultArea=['400000', '401000'] - React

**Comment by dwqs** [comment]
👍 @rplees

**Comment by dwqs** [comment]
v5版本已近接近一个通用的联动选择器了，数据格式见 [area-data](https://github.com/dwqs/area-data)

**Comment by rplees** [comment]
@dwqs 好的,这就去试试看 [强]
