### ISSUE TITLE
希望能增加Size属性

### ISSUE THREAD

**Issue by xingyibiao** [dwqs/vue-area-linkage#3]
增加size属性， 在表单中更好应用

**Comment by dwqs** [comment]
增加 size 属性是调整组件的大小吗？还是其它需求场景？

**Comment by xingyibiao** [comment]
调整组件大小用。

**Comment by dwqs** [comment]
这个可以通过样式覆盖就好

**Comment by xingyibiao** [comment]
我目前的解决方案就是用样式覆盖的。 我觉得如果prop增加size属性可能会更好 ， default为small

**Comment by dwqs** [comment]
可以考虑

**Comment by dwqs** [comment]
已经添加： https://dwqs.github.io/vue-area-linkage/
