### ISSUE TITLE
bug，某些省直辖市选择后，会报错

### ISSUE THREAD

**Issue by sowee121** [dwqs/vue-area-linkage#30]
湖北省下的仙桃、天门、潜江三个省直辖市都出现这个报错

![1522752327 1](https://user-images.githubusercontent.com/18671659/38245079-55df24ac-376f-11e8-9fed-02118cfc9446.jpg)
![1522752352 1](https://user-images.githubusercontent.com/18671659/38245084-5ae7c5da-376f-11e8-945a-305ad7fef930.jpg)

**Comment by dwqs** [comment]
能看下代码？  我在 [demo](https://dwqs.github.io/vue-area-linkage/) 上选择这几个地区并没有报错

**Comment by dwqs** [comment]
@sowee121  看了下省市数据 ：http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2016/42.html  湖北省下没有这几个市了 全部归属到 省级行政区划了：http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2016/42/4290.html

**Comment by dwqs** [comment]
@sowee121 已经修复了 但是数据的问题还的等 [china-area-data](https://github.com/airyland/china-area-data) 更新

**Comment by dwqs** [comment]
@sowee121 升级到 3.0.2
