### ISSUE TITLE
在v4中将不再提供街道选择，仅提供省市区选择

### ISSUE THREAD

**Issue by dwqs** [dwqs/vue-area-linkage#31]
如题，v4 publish 之后将关闭此 issue

**Comment by xianengqi** [comment]
错误码  [vue-area-linkage]: 2.0版本需要单独引入 street.js: https://github.com/dwqs/area-data

**Comment by dwqs** [comment]
@xianengqi 没有引入街道数据吧  目前 vue-area-linkage 依赖的 area-data 版本是 v3 的  你可以看看 area-data 的  README

**Comment by xianengqi** [comment]
@dwqs 用起来很棒！！！

**Comment by dwqs** [comment]
@xianengqi 多谢

**Comment by dwqs** [comment]
[v4.0.0](https://github.com/dwqs/vue-area-linkage/releases/tag/v4.0.0)
