### ISSUE TITLE
关于area-cascader 赋值问题

### ISSUE THREAD

**Issue by samchenws** [dwqs/vue-area-linkage#33]
第一次赋值 假设为
辽宁省/丹东市/凤城市

代码如下
   <el-form-item label="所在地区" prop="addressCode">
                            <area-cascader style="width:100%" :level="1" v-model='query'></area-cascader>
                        </el-form-item>
第二次我将query清空，但是还是显示上面的 辽宁省/丹东市/凤城市
请问下有清空的方法或方式么？

**Comment by samchenws** [comment]
`   <el-form-item label="所在地区" prop="addressCode">
                            <area-cascader style="width:100%" :level="1" v-model='query'></area-cascader>

                        </el-form-item>`

**Comment by xianengqi** [comment]
返回值是一个数组，，我如何把返回值写成一个字符串哇，，后端同学给我的接口要求是字符串

**Comment by samchenws** [comment]
数组.toString() @xianengqi

**Comment by xianengqi** [comment]
@Thank you!!!!

**Comment by dwqs** [comment]
@samchenws 暂时没有清空的方法

**Comment by samchenws** [comment]
@dwqs 貌似2次绑定也是第一次的值

**Comment by dwqs** [comment]
@samchenws 2次绑定?

**Comment by samchenws** [comment]
``  <area-cascader style="width:100%" :level="1" v-model='query'></area-cascader>
修改query的值好像也不会变
