### ISSUE TITLE
一级下拉选框选择后怎么让后级的下拉选框取消默认选择？

### ISSUE THREAD

**Issue by towill** [dwqs/vue-area-linkage#39]
一级下拉选框选择后怎么让后级的下拉选框取消默认选择？

**Comment by dwqs** [comment]
暂不支持

**Comment by towill** [comment]
好的  谢谢

**Comment by DAHU123** [comment]
一级下拉选框选择后怎么让后级的下拉选框取消默认选择？现在我这边可以用代码去实现这个需求吗?我现在也是想要取消猴急的下拉选框的默认选择呀?

**Comment by DAHU123** [comment]
大神   您什么时候更新代码来解决现在我们提出来的这个需求呀?给一个具体的时间可以吗?

**Comment by dwqs** [comment]
「取消后级的下拉框」是指不进行联动？

**Comment by DAHU123** [comment]
对的  就是不进行联动

**Comment by DAHU123** [comment]
当我选择省级别的选项以后，市级别的不是默认选中第一个选项，而是请选择，就是不进行联动

**Comment by dwqs** [comment]
我这两天找时间看下

**Comment by DAHU123** [comment]
尽快更新吧　　可以把是否联动开放出来一个接口　　让用户自定义选择

**Comment by dwqs** [comment]
`v5.0.2` 增加了 `isLinkage` 属性  设置为 `false` 默认不进行联动

**Comment by DAHU123** [comment]
多谢大神    现在已经把你的更新都应用到项目上了     这个开放出来的接口很管用!
