### ISSUE TITLE
设置默认值代码

### ISSUE THREAD

**Issue by aisir** [dwqs/vue-area-linkage#4]
解析出来是这个样子的
“'选择省', '选择市'] v-model='selected'>”

**Comment by dwqs** [comment]
能更详细说明下？

**Comment by aisir** [comment]
【默认形式】正常解析展现
![2017-10-18 14-41-11](https://user-images.githubusercontent.com/12620193/31704102-697faec2-b412-11e7-8608-69ccee2614b7.png)

将【设置placeholders】这段代码 放到 <area-select :placeholders=['选择省', '选择市'] v-model='selected'></area-select>
自己的template 代码中
<div class="form-group">
    <input type="number" class="form-control" name="height" placeholder="身高（cm）">
  </div>
    <div class="form-group">
    <area-select :placeholders=['选择省', '选择市'] v-model='selected'></area-select>
  </div>
   <div class="form-group">
    <input type="password" class="form-control" name="education" placeholder="学历">
  </div>
是这个样子
![2017-10-18 14-40-08](https://user-images.githubusercontent.com/12620193/31704085-512551ce-b412-11e7-919e-512cb8fea5a2.png)

**Comment by dwqs** [comment]
有报错信息吗？这是我在 [demo](https://github.com/dwqs/vue-area-linkage/blob/master/gh/components/main/placeholders.vue) 中的用法  木有问题

**Comment by aisir** [comment]
![2017-10-18 14-53-47](https://user-images.githubusercontent.com/12620193/31704503-46768214-b414-11e7-898e-2e767e82409e.png)
/dk
好吧，我以为会是酱紫的

**Comment by dwqs** [comment]
还是不能正常展示？？？？？ 从你的描述看，貌似是被当做纯文本给解析了
