### ISSUE TITLE
change事件有问题

### ISSUE THREAD

**Issue by DAHU123** [dwqs/vue-area-linkage#44]
页面初始化配置完这个三级联动的插件之后，当我选择省，后面的区和市都没有选择，对应的change事件没有被触发，然后选择市，再选择区，选择完区以后，change事件才被触发；接下来重新选择省，change事件被触发了；
期望：初始化载入页面，三级联动插件配置完以后，第一次选择省change事件可以被触发

**Comment by dwqs** [comment]
`v-model`  绑定的值有变化吗？

**Comment by dwqs** [comment]
我尽快处理下

**Comment by DAHU123** [comment]
大神，你更新这个ｂｕｇ的时候通知我一下下，我下一个版本的项目就要正式把这个插件集成进去了，就等这个change事件的问题解决呢！多谢了！

**Comment by dwqs** [comment]
好的

**Comment by dwqs** [comment]
v5.1.0 的版本修复了这个，并将 `isLinkage` 更改了 `disableLinkage` 属性

**Comment by DAHU123** [comment]
多谢大神!我改天更新一下看看.
