### ISSUE TITLE
样式有些问题

### ISSUE THREAD

**Issue by stone009** [dwqs/vue-area-linkage#46]
好像有些错位，修改样式也不起作用。
![image](https://user-images.githubusercontent.com/25975586/47781470-b5a1ff80-dd38-11e8-95ad-1484bcf097e0.png)

```
<el-form-item prop="areas" label="地区">
      <area-select :level="2" v-model="shopForm.areas" :data="pca" size="large" class="areas-wrapper" type="text"/>
    </el-form-item>
```

**Comment by DAHU123** [comment]
滚动条的样式如何去调呀？现在我想要变更一下下拉菜单中滚动条的样式．却没有像之前的版本那样定位到滚动条所在的元素．求大神支招怎么破！

**Comment by dwqs** [comment]
https://segmentfault.com/a/1190000003708894

**Comment by DAHU123** [comment]
具体应该怎么来定义呀？就直接这样子::-webkit-scrollbar-thumb行了吗？需要什么类名吗？

**Comment by DAHU123** [comment]
样式怎么会没有办法覆盖呢?用上面那个链接，自定义的样式无法覆盖插件自带的，怎么破？

**Comment by dwqs** [comment]
你可以看下组件中自定义滚动条的样式[代码](https://github.com/dwqs/vue-area-linkage/blob/master/src/index.less#L199-L220)  然后通过选择器进行覆盖

**Comment by DAHU123** [comment]
.area-selectable-list-wrap::-webkit-scrollbar{
        width: 4px!important;
    }
我现在在应用这个组件的vue文件中写下了上面的代码     没有进行覆盖  还是原有的样式    这个怎么解决呀?

**Comment by dwqs** [comment]
组件样式的优先级不够？

**Comment by dwqs** [comment]
长时间无响应 关闭
