### ISSUE TITLE
关于动态绑定值的问题

### ISSUE THREAD

**Issue by ZhiGang-Fang** [dwqs/vue-area-linkage#6]
默认情况下是可以通过v-model绑定选中的，但是从api 请求回来的数据时，无法将数据重置到上次保存的数据，麻烦帮忙看看谢谢！

![1](https://user-images.githubusercontent.com/24228407/33361944-1c5b3e12-d515-11e7-937e-6a4033854746.png)

![2](https://user-images.githubusercontent.com/24228407/33361960-27660512-d515-11e7-8fde-3b8cf8bba819.png)

这样是可以选中的，但是如下图就选不中了
![3](https://user-images.githubusercontent.com/24228407/33362048-8d7558e4-d515-11e7-9d7e-f94a30166bd8.png)

还有就是怎么初始化值type=‘all’ 时为请选择？

**Comment by dwqs** [comment]
返回的数据是什么？

**Comment by ZhiGang-Fang** [comment]
detail.provinceId="110000",
detail.cityId="110100",
detail.districtId="110101",

**Comment by dwqs** [comment]
我这使用的是正常的

```html
<template>
     // ...
     <area-select v-model="areaSelected"></area-select>
    // ...
</template>

<script>
     export default {
             data () {
                     return {
                            areaSelected: []
                     }
             },
             computed: {
                     ...mapGetters({
                              'address': 'getAddress'
                      })
             },
             watch: {
                      address (val) {
                               this.areaSelected = ['xxx', 'xxxx'];  // 处理 val
                       }
             }
     }
</script>
```



```

**Comment by GR07** [comment]
我想问下 如何重置数据啊 把v-model绑定的值初始化 没有效果啊

**Comment by dwqs** [comment]
@GR07 https://github.com/dwqs/vue-area-linkage/issues/19
