### ISSUE TITLE
在level设置为2的时候，无法选中没有区的城市，如广东-东莞，或广东-中山

### ISSUE THREAD

**Issue by jiutianxuannan** [dwqs/vue-area-linkage#7]

**Comment by dwqs** [comment]
能贴下你的代码吗

**Comment by jiutianxuannan** [comment]
你demo实例中，倒数第二个设置默认值的demo中，无法选中广东-东莞，广东中山

**Comment by dwqs** [comment]
![image](https://user-images.githubusercontent.com/7871813/34331053-57a4c7ba-e95e-11e7-8180-429c4d6f9939.png)

东莞和中山都没有下设的区了

**Comment by jiutianxuannan** [comment]
没错，但是我个人觉得，没有区的城市也能直接选中，而不是点击该城市的时候毫无反应，最近项目中要用到该组件作为地址选择器，这样子广东东莞的地址就无法选中，貌似国内没有区的城市应该也有一部分的，希望可以修复下该Bug

**Comment by dwqs** [comment]
在三级联动选择时，如果市级下面没有区时，默认提供「市辖区」选择项

**Comment by jiutianxuannan** [comment]
嗯，在三级联动时候，有区就的显示省市区，没有区的，就显示省市，如广东东莞，用市辖区这个概念貌似觉得不太妥当，因为东莞中山之类的城市本身不属于市辖区，个人觉得

**Comment by dwqs** [comment]
已经修复

**Comment by jiutianxuannan** [comment]
感谢，什么时候发新版本？

**Comment by dwqs** [comment]
已经发了 v1.2.2
