### ISSUE TITLE
请问数组项是文本时，怎么设置默认值

### ISSUE THREAD

**Issue by dafeng17** [dwqs/vue-area-linkage#8]
area-cascader type='text' :level='1' v-model="value1" placeholder="请选择地址"></area-cascader
我用的是文本的数据，设置完地址后，要编辑修改数据是，怎么设置默认值（上回文本数据）？

**Comment by dwqs** [comment]
你说的文本数据是指？

**Comment by dafeng17** [comment]
<img width="904" alt="tu" src="https://user-images.githubusercontent.com/17774547/34359468-357c2c6a-ea93-11e7-9fef-64441bf6a60c.png">

**Comment by dafeng17** [comment]
就是这种使用，但我保存到后台数据，是省市区文字，现在需要编辑修改省市区，怎么把文字赋值进去？

**Comment by dwqs** [comment]
展示时的编码数字是行政区域的编码吗？如果是的话 可以试试通过行政区域编码获取其对应的行政区域文本 再设置到 `v-model` 绑定的值

**Comment by dafeng17** [comment]
嗯嗯，但这样还要多一步行政区域编码转化行政区域文本。现在组件能不能实现第一种引入，就是行政区域文本也能赋值到组件里，而不是通过行政区域编码赋值，（默认赋值功能）

**Comment by dwqs** [comment]
现在就支持区域文本用于默认赋值

**Comment by dafeng17** [comment]
![tu3](https://user-images.githubusercontent.com/17774547/34368749-40e9994e-eaf1-11e7-8ab6-d8328f1031da.png)
v-model 绑定这样的数据，但没生效，格式错了？

**Comment by dwqs** [comment]
我刚试了 `v-model` 绑定 `['广东省', '深圳市', '南山区']` 是没问题  但绑定 `['山西省', '阳泉市', '郊区']` 会报错 我找下原因

**Comment by dwqs** [comment]
更新版本到 1.2.3

**Comment by dafeng17** [comment]
v-model 绑定 ['广东省', '深圳市', '南山区']用的是这种吗:
<area-cascader type='text' :level='1' v-model="value2" placeholder="请选择地址"></area-cascader>

**Comment by dwqs** [comment]
是的
