### ISSUE TITLE
地址列表，需要修改省市区，多条数据的v-model值是对的，但显示的一直不变

### ISSUE THREAD

**Issue by dafeng17** [dwqs/vue-area-linkage#9]
![tu4](https://user-images.githubusercontent.com/17774547/34435108-1677ea7c-ecc6-11e7-90b2-2e6b906141f5.png)
![tu5](https://user-images.githubusercontent.com/17774547/34435286-4eebdc00-ecc7-11e7-88a3-761184fdfc39.png)

![tu6](https://user-images.githubusercontent.com/17774547/34435112-1e64bb16-ecc6-11e7-891b-45ed28b10d1b.png)
列表修改省市区，v-model值是正确的，但显示的内容一直不变

**Comment by dwqs** [comment]
有简单的 demo 可以看下不

**Comment by dafeng17** [comment]
<template>
  <div class="hello">
    <h1>省市区</h1>
    <div v-for="item in list">
      <div>
        <div @click='xiugai(item)' style='cursor:pointer;border:1px solid;width:50px;heigth:20px;'>修改</div>{{ item.address }}<br><br><br><br>
      </div>
    </div>
    <div v-if='modelbool' style="border:1px solid;">
      <area-select type='text' :level='2' v-model="selected"></area-select>
    </div>
  </div>
</template>

<script>
export default {
  name: 'HelloWorld',
  data () {
    return {
      modelbool:false,
      list: [
        {
          address:'福建省-泉州市-南安市'
        },
        {
          address:'浙江省-杭州市-西湖区'
        }
      ]
    }
  },
  methods: {
    xiugai (item) {
      this.modelbool = true
      debugger
      this.selected = item.address.split('-')
    }
  }
}
</script>

版本：1.2.3

**Comment by dafeng17** [comment]
https://github.com/dafeng17/address
小demo，点击修改时，点第二个数据变化了，但组件里文字不变

**Comment by dwqs** [comment]
我看下

**Comment by dwqs** [comment]
跑了你的demo 我这是变化的

**Comment by dafeng17** [comment]
![tu1](https://user-images.githubusercontent.com/17774547/34486810-794e6d12-f00c-11e7-9e6a-a7ca8033e9a8.png)
点修改，第二次数据是变了，但文字没变啊？

**Comment by dwqs** [comment]
组件只在 `created` 的时候进行一次默认值的设置，之后就不会再更改默认值了

**Comment by dwqs** [comment]
已经修复 请升级到1.2.5
